export const TASK_MANAGER_CONSTANTS = {
    CONST_ADD_TASK: 'CONST_ADD_TASK',
    CONST_VIEW_TASK: 'CONST_VIEW_TASK',
    CONST_BTN_ADD_TASK: 'Add',
    CONST_BTN_UPDATE_TASK: 'Update',
    CONST_DATE_FORMAT: 'DD-MMM-YYYY'
}
